#! /usr/bin/env python

import sys
import subprocess

# query osX adressbook
def ask_osxabook(name):
    p = subprocess.Popen(["contacts", "-sSf", "%e\t%n", name], stdout=subprocess.PIPE)
    output, err = p.communicate()
    #result = '\n'.join(output.split('\n')[1:])
    print output

# query ldap
def ask_ldap(name):
    print ""

def ask_mutt(name):
    print ""


if (len(sys.argv) == 2):
    search = sys.argv[1]
    ask_osxabook(search)
else:
    sys.stderr.write("abook search\n")
    sys.exit(1)
