#! /usr/bin/env python
import subprocess
import sys

# commandline to get servicetag
cmd="sudo dmidecode | awk '/Serial Number/ {print $3;exit}'"

## get service tag ##
def get_st():
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
    (output, err) = p.communicate()
    p_status = p.wait()
    return output.replace('\n', ' ')

## print information ##
def print_info(input):
    print "------------------------------"
    print "Service Tag: ", input
    print "Express Tag: ", int(input,36)
    print "------------------------------"

## start app ##
del sys.argv[0] # we dont need the scriptname
arg = len(sys.argv)
if arg < 1:
    if sys.stdin.isatty():
        st=get_st()
        print_info(st)
    else:
        for line in sys.stdin:
            print_info(line.replace('\n', ' '))
else:
    for st in sys.argv:
        print_info(st)
